import { testFactory } from './test'

const test = testFactory('no-pagination')

test('does not set prev/next links of autogenerated sidebar group pages when pagination is disabled in the config', async ({
  getPage,
}) => {
  const page = await getPage()

  await page.expectPrevNextLinks('updates', [
    {
      url: '/a/',
      expected: {
        prev: null,
        next: null,
      },
    },
    {
      url: '/b/',
      expected: {
        prev: null,
        next: null,
      },
    },
    {
      url: '/sub-1/a/',
      expected: {
        // Prev link and label defined in the file frontmatter.
        prev: { href: '/', label: 'Home' },
        next: null,
      },
    },
    {
      url: '/sub-1/b/',
      expected: {
        prev: null,
        next: null,
      },
    },
  ])
})
